### ISSUE TITLE
v3.1.0 - this.phoneInput.intlTelInput is not a function

### ISSUE THREAD

**Issue by BnitoBzh** [qonto/ember-phone-input#155]
After an upgrade from 3.0.0 to 3.1.0 i get this error : `this.phoneInput.intlTelInput is not a function`
This method is called in the `phone-input` component.

**Comment by dcyriller** [comment]
The fix is here: https://github.com/qonto/ember-phone-input/pull/154 (cc @Turbo87)
